# Generated by Django 4.2.7 on 2026-01-20 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='board_thumbnails/')),
                ('is_archived', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='courses.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StarredBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('version_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='boards.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='BoardShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'Can Edit')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='boards.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='starred_by',
            field=models.ManyToManyField(related_name='starred_boards', through='boards.StarredBoard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='starredboard',
            index=models.Index(fields=['user', '-created_at'], name='boards_star_user_id_628d06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='starredboard',
            unique_together={('user', 'board')},
        ),
        migrations.AddIndex(
            model_name='boardversion',
            index=models.Index(fields=['board', '-version_number'], name='boards_boar_board_i_94f6be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boardversion',
            unique_together={('board', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='boardshare',
            index=models.Index(fields=['user', '-created_at'], name='boards_boar_user_id_293cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='boardshare',
            index=models.Index(fields=['board'], name='boards_boar_board_i_e0693b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boardshare',
            unique_together={('board', 'user')},
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['owner', '-updated_at'], name='boards_boar_owner_i_4420f5_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['course'], name='boards_boar_course__0606a3_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['is_archived'], name='boards_boar_is_arch_10fefd_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['is_template'], name='boards_boar_is_temp_18e980_idx'),
        ),
    ]
