# Generated by Django 4.2.7 on 2026-02-04 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.CharField(blank=True, choices=[('course-material', 'Course Material'), ('student-notes', 'Student Notes'), ('study-planner', 'Study Planner'), ('kanban', 'Kanban')], default='course-material', max_length=20),
        ),
        migrations.CreateModel(
            name='BoardInviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'Can Edit')], default='view', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Null = unlimited uses', null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='boards.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invite_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='boards_boar_token_7b004d_idx'), models.Index(fields=['board', 'is_active'], name='boards_boar_board_i_9a1ce1_idx')],
            },
        ),
    ]
